/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Administracion: typeof import('./components/administracion/Administracion.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    CatalogosDropdown: typeof import('./components/menu/CatalogosDropdown.vue')['default']
    CrudTablePage: typeof import('./components/catalogos/CrudTablePage.vue')['default']
    DialogGlobal: typeof import('./components/DialogGlobal.vue')['default']
    InsumosDropdown: typeof import('./components/menu/InsumosDropdown.vue')['default']
    LogoutComponent: typeof import('./components/menu/LogoutComponent.vue')['default']
    MenuSubmenusComponent: typeof import('./components/menu/MenuSubmenusComponent.vue')['default']
    ModalComponent: typeof import('./components/catalogos/ModalComponent.vue')['default']
    Reaseguro: typeof import('./components/reaseguro/Reaseguro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./components/catalogos/SearchComponent.vue')['default']
    TransformacionInsumoCard: typeof import('./components/TransformacionInsumoCard.vue')['default']
  }
}
