/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Administracion: typeof import('./components/administracion/Administracion.vue')['default']
    AdministracionSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/AdministracionSection.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    CatalogosDropdown: typeof import('./components/menu/CatalogosDropdown.vue')['default']
    CoberturasSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/CoberturasSection.vue')['default']
    ComisionesRateOnLineSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/ComisionesRateOnLineSection.vue')['default']
    CorretajeSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/CorretajeSection.vue')['default']
    CrudTablePage: typeof import('./components/catalogos/CrudTablePage.vue')['default']
    CumulosSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/CumulosSection.vue')['default']
    DetallesProporcionalesSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/DetallesProporcionalesSection.vue')['default']
    DialogGlobal: typeof import('./components/DialogGlobal.vue')['default']
    ExcedentesSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/ExcedentesSection.vue')['default']
    GeneralesSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/GeneralesSection.vue')['default']
    InsumosDropdown: typeof import('./components/menu/InsumosDropdown.vue')['default']
    IntermediariosSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/IntermediariosSection.vue')['default']
    LogoutComponent: typeof import('./components/menu/LogoutComponent.vue')['default']
    MenuSubmenusComponent: typeof import('./components/menu/MenuSubmenusComponent.vue')['default']
    ModalComponent: typeof import('./components/catalogos/ModalComponent.vue')['default']
    PolizasFacultativasSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/PolizasFacultativasSection.vue')['default']
    ProporcionPrimaSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/ProporcionPrimaSection.vue')['default']
    ReaseguradoresSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/ReaseguradoresSection.vue')['default']
    Reaseguro: typeof import('./components/reaseguro/Reaseguro.vue')['default']
    ReinstalacionesSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/ReinstalacionesSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./components/catalogos/SearchComponent.vue')['default']
    SnackBarComponent: typeof import('./components/general/SnackBarComponent.vue')['default']
    TabSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/TabSection.vue')['default']
    TarifaSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/TarifaSection.vue')['default']
    TransformacionInsumoCard: typeof import('./components/TransformacionInsumoCard.vue')['default']
    WindowSection: typeof import('./components/reaseguro/contratos/accidentes_enfermedades/nuevo/WindowSection.vue')['default']
  }
}
