/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/administracion/AdministracionPage': RouteRecordInfo<'/administracion/AdministracionPage', '/administracion/AdministracionPage', Record<never, never>, Record<never, never>>,
    '/administracion/CalculosPage': RouteRecordInfo<'/administracion/CalculosPage', '/administracion/CalculosPage', Record<never, never>, Record<never, never>>,
    '/administracion/CatalogosPage': RouteRecordInfo<'/administracion/CatalogosPage', '/administracion/CatalogosPage', Record<never, never>, Record<never, never>>,
    '/administracion/ContratosReasegPage': RouteRecordInfo<'/administracion/ContratosReasegPage', '/administracion/ContratosReasegPage', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/LoginC': RouteRecordInfo<'/auth/LoginC', '/auth/LoginC', Record<never, never>, Record<never, never>>,
    '/catalogos/ClasificacionCoberturaPage': RouteRecordInfo<'/catalogos/ClasificacionCoberturaPage', '/catalogos/ClasificacionCoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CoberturaPage': RouteRecordInfo<'/catalogos/CoberturaPage', '/catalogos/CoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CriteriosAsignacionPage': RouteRecordInfo<'/catalogos/CriteriosAsignacionPage', '/catalogos/CriteriosAsignacionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CriteriosCoberturaPage': RouteRecordInfo<'/catalogos/CriteriosCoberturaPage', '/catalogos/CriteriosCoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/DistribucionCesionPage': RouteRecordInfo<'/catalogos/DistribucionCesionPage', '/catalogos/DistribucionCesionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EntidadFederativaPage': RouteRecordInfo<'/catalogos/EntidadFederativaPage', '/catalogos/EntidadFederativaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EstatusPage': RouteRecordInfo<'/catalogos/EstatusPage', '/catalogos/EstatusPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EstatusReciboPage': RouteRecordInfo<'/catalogos/EstatusReciboPage', '/catalogos/EstatusReciboPage', Record<never, never>, Record<never, never>>,
    '/catalogos/ExtensionPage': RouteRecordInfo<'/catalogos/ExtensionPage', '/catalogos/ExtensionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FormaContractualPage': RouteRecordInfo<'/catalogos/FormaContractualPage', '/catalogos/FormaContractualPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FormaPagoPage': RouteRecordInfo<'/catalogos/FormaPagoPage', '/catalogos/FormaPagoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FumadorPage': RouteRecordInfo<'/catalogos/FumadorPage', '/catalogos/FumadorPage', Record<never, never>, Record<never, never>>,
    '/catalogos/IntermediariosPage': RouteRecordInfo<'/catalogos/IntermediariosPage', '/catalogos/IntermediariosPage', Record<never, never>, Record<never, never>>,
    '/catalogos/MonedaPage': RouteRecordInfo<'/catalogos/MonedaPage', '/catalogos/MonedaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/OperacionesRamosPage': RouteRecordInfo<'/catalogos/OperacionesRamosPage', '/catalogos/OperacionesRamosPage', Record<never, never>, Record<never, never>>,
    '/catalogos/PerfilPage': RouteRecordInfo<'/catalogos/PerfilPage', '/catalogos/PerfilPage', Record<never, never>, Record<never, never>>,
    '/catalogos/PtuPage': RouteRecordInfo<'/catalogos/PtuPage', '/catalogos/PtuPage', Record<never, never>, Record<never, never>>,
    '/catalogos/ReaseguradoresPage': RouteRecordInfo<'/catalogos/ReaseguradoresPage', '/catalogos/ReaseguradoresPage', Record<never, never>, Record<never, never>>,
    '/catalogos/SexoPage': RouteRecordInfo<'/catalogos/SexoPage', '/catalogos/SexoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoAsignacionPage': RouteRecordInfo<'/catalogos/TipoAsignacionPage', '/catalogos/TipoAsignacionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoEndosoPage': RouteRecordInfo<'/catalogos/TipoEndosoPage', '/catalogos/TipoEndosoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoReaseguroPage': RouteRecordInfo<'/catalogos/TipoReaseguroPage', '/catalogos/TipoReaseguroPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposCambioPage': RouteRecordInfo<'/catalogos/TiposCambioPage', '/catalogos/TiposCambioPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposCapturaPage': RouteRecordInfo<'/catalogos/TiposCapturaPage', '/catalogos/TiposCapturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposContratoPage': RouteRecordInfo<'/catalogos/TiposContratoPage', '/catalogos/TiposContratoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoTarifaPage': RouteRecordInfo<'/catalogos/TipoTarifaPage', '/catalogos/TipoTarifaPage', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/insumos/CifrasControlPage': RouteRecordInfo<'/insumos/CifrasControlPage', '/insumos/CifrasControlPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormCoberturasPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormCoberturasPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormCoberturasPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormComisionesPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormComisionesPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormComisionesPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormCorretajePageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormCorretajePageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormCorretajePageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormDetallesPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormDetallesPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormDetallesPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormGeneralesPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormGeneralesPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormGeneralesPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormIntermediariosPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormIntermediariosPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormIntermediariosPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/FormReaseguradoresPageM': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/FormReaseguradoresPageM', '/reaseguro/Contratos/Danios/ModificarContrato/FormReaseguradoresPageM', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContrato/ModificarContratoPag': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContrato/ModificarContratoPag', '/reaseguro/Contratos/Danios/ModificarContrato/ModificarContratoPag', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/ModificarContratosPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/ModificarContratosPage', '/reaseguro/Contratos/Danios/ModificarContratosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormCoberturasPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormCoberturasPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormCoberturasPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormComisionesPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormComisionesPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormComisionesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormCorretajePage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormCorretajePage', '/reaseguro/Contratos/Danios/NuevoContrato/FormCorretajePage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormDetallesPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormDetallesPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormDetallesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormGeneralesPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormGeneralesPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormGeneralesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormIntermediariosPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormIntermediariosPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormIntermediariosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContrato/FormReaseguradoresPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContrato/FormReaseguradoresPage', '/reaseguro/Contratos/Danios/NuevoContrato/FormReaseguradoresPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/NuevoContratoPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/NuevoContratoPage', '/reaseguro/Contratos/Danios/NuevoContratoPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Danios/VisualizarContratosPage': RouteRecordInfo<'/reaseguro/Contratos/Danios/VisualizarContratosPage', '/reaseguro/Contratos/Danios/VisualizarContratosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/ModificarContratosVidaPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/ModificarContratosVidaPage', '/reaseguro/Contratos/Vida/ModificarContratosVidaPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegCoberturaPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegCoberturaPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegCoberturaPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegComisionEsPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegComisionEsPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegComisionEsPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegGeneralPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegGeneralPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegGeneralPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegPTUPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegPTUPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegPTUPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionIntermediariosPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionIntermediariosPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionIntermediariosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionReaseguradoresPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionReaseguradoresPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionReaseguradoresPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormDatosPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormDatosPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormDatosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormGeneralDatosPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormGeneralDatosPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormGeneralDatosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/FormPolizasFacultativasPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/FormPolizasFacultativasPage', '/reaseguro/Contratos/Vida/NuevoContratoVida/FormPolizasFacultativasPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVida/ModalEnviarDatos': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVida/ModalEnviarDatos', '/reaseguro/Contratos/Vida/NuevoContratoVida/ModalEnviarDatos', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/NuevoContratoVidaPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/NuevoContratoVidaPage', '/reaseguro/Contratos/Vida/NuevoContratoVidaPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/Vida/VisualizarContratosVidaPage': RouteRecordInfo<'/reaseguro/Contratos/Vida/VisualizarContratosVidaPage', '/reaseguro/Contratos/Vida/VisualizarContratosVidaPage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/administracion/AdministracionPage.vue': {
      routes: '/administracion/AdministracionPage'
      views: never
    }
    'src/pages/administracion/CalculosPage.vue': {
      routes: '/administracion/CalculosPage'
      views: never
    }
    'src/pages/administracion/CatalogosPage.vue': {
      routes: '/administracion/CatalogosPage'
      views: never
    }
    'src/pages/administracion/ContratosReasegPage.vue': {
      routes: '/administracion/ContratosReasegPage'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
    'src/pages/auth/LoginC.vue': {
      routes: '/auth/LoginC'
      views: never
    }
    'src/pages/catalogos/ClasificacionCoberturaPage.vue': {
      routes: '/catalogos/ClasificacionCoberturaPage'
      views: never
    }
    'src/pages/catalogos/CoberturaPage.vue': {
      routes: '/catalogos/CoberturaPage'
      views: never
    }
    'src/pages/catalogos/CriteriosAsignacionPage.vue': {
      routes: '/catalogos/CriteriosAsignacionPage'
      views: never
    }
    'src/pages/catalogos/CriteriosCoberturaPage.vue': {
      routes: '/catalogos/CriteriosCoberturaPage'
      views: never
    }
    'src/pages/catalogos/DistribucionCesionPage.vue': {
      routes: '/catalogos/DistribucionCesionPage'
      views: never
    }
    'src/pages/catalogos/EntidadFederativaPage.vue': {
      routes: '/catalogos/EntidadFederativaPage'
      views: never
    }
    'src/pages/catalogos/EstatusPage.vue': {
      routes: '/catalogos/EstatusPage'
      views: never
    }
    'src/pages/catalogos/EstatusReciboPage.vue': {
      routes: '/catalogos/EstatusReciboPage'
      views: never
    }
    'src/pages/catalogos/ExtensionPage.vue': {
      routes: '/catalogos/ExtensionPage'
      views: never
    }
    'src/pages/catalogos/FormaContractualPage.vue': {
      routes: '/catalogos/FormaContractualPage'
      views: never
    }
    'src/pages/catalogos/FormaPagoPage.vue': {
      routes: '/catalogos/FormaPagoPage'
      views: never
    }
    'src/pages/catalogos/FumadorPage.vue': {
      routes: '/catalogos/FumadorPage'
      views: never
    }
    'src/pages/catalogos/IntermediariosPage.vue': {
      routes: '/catalogos/IntermediariosPage'
      views: never
    }
    'src/pages/catalogos/MonedaPage.vue': {
      routes: '/catalogos/MonedaPage'
      views: never
    }
    'src/pages/catalogos/OperacionesRamosPage.vue': {
      routes: '/catalogos/OperacionesRamosPage'
      views: never
    }
    'src/pages/catalogos/PerfilPage.vue': {
      routes: '/catalogos/PerfilPage'
      views: never
    }
    'src/pages/catalogos/PtuPage.vue': {
      routes: '/catalogos/PtuPage'
      views: never
    }
    'src/pages/catalogos/ReaseguradoresPage.vue': {
      routes: '/catalogos/ReaseguradoresPage'
      views: never
    }
    'src/pages/catalogos/SexoPage.vue': {
      routes: '/catalogos/SexoPage'
      views: never
    }
    'src/pages/catalogos/TipoAsignacionPage.vue': {
      routes: '/catalogos/TipoAsignacionPage'
      views: never
    }
    'src/pages/catalogos/TipoEndosoPage.vue': {
      routes: '/catalogos/TipoEndosoPage'
      views: never
    }
    'src/pages/catalogos/TipoReaseguroPage.vue': {
      routes: '/catalogos/TipoReaseguroPage'
      views: never
    }
    'src/pages/catalogos/TiposCambioPage.vue': {
      routes: '/catalogos/TiposCambioPage'
      views: never
    }
    'src/pages/catalogos/TiposCapturaPage.vue': {
      routes: '/catalogos/TiposCapturaPage'
      views: never
    }
    'src/pages/catalogos/TiposContratoPage.vue': {
      routes: '/catalogos/TiposContratoPage'
      views: never
    }
    'src/pages/catalogos/TipoTarifaPage.vue': {
      routes: '/catalogos/TipoTarifaPage'
      views: never
    }
    'src/pages/Home.vue': {
      routes: '/Home'
      views: never
    }
    'src/pages/insumos/CifrasControlPage.vue': {
      routes: '/insumos/CifrasControlPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormCoberturasPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormCoberturasPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormComisionesPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormComisionesPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormCorretajePageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormCorretajePageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormDetallesPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormDetallesPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormGeneralesPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormGeneralesPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormIntermediariosPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormIntermediariosPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/FormReaseguradoresPageM.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/FormReaseguradoresPageM'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContrato/ModificarContratoPag.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContrato/ModificarContratoPag'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/ModificarContratosPage.vue': {
      routes: '/reaseguro/Contratos/Danios/ModificarContratosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormCoberturasPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormCoberturasPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormComisionesPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormComisionesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormCorretajePage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormCorretajePage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormDetallesPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormDetallesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormGeneralesPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormGeneralesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormIntermediariosPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormIntermediariosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContrato/FormReaseguradoresPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContrato/FormReaseguradoresPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/NuevoContratoPage.vue': {
      routes: '/reaseguro/Contratos/Danios/NuevoContratoPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Danios/VisualizarContratosPage.vue': {
      routes: '/reaseguro/Contratos/Danios/VisualizarContratosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/ModificarContratosVidaPage.vue': {
      routes: '/reaseguro/Contratos/Vida/ModificarContratosVidaPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegCoberturaPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegCoberturaPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegComisionEsPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegComisionEsPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegGeneralPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegGeneralPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegPTUPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfigReasegPTUPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionIntermediariosPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionIntermediariosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionReaseguradoresPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormConfiguracionReaseguradoresPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormDatosPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormDatosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormGeneralDatosPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormGeneralDatosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/FormPolizasFacultativasPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/FormPolizasFacultativasPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVida/ModalEnviarDatos.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVida/ModalEnviarDatos'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/NuevoContratoVidaPage.vue': {
      routes: '/reaseguro/Contratos/Vida/NuevoContratoVidaPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/Vida/VisualizarContratosVidaPage.vue': {
      routes: '/reaseguro/Contratos/Vida/VisualizarContratosVidaPage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
