/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/administracion/AdministracionPage': RouteRecordInfo<'/administracion/AdministracionPage', '/administracion/AdministracionPage', Record<never, never>, Record<never, never>>,
    '/administracion/CalculosPage': RouteRecordInfo<'/administracion/CalculosPage', '/administracion/CalculosPage', Record<never, never>, Record<never, never>>,
    '/administracion/CatalogosPage': RouteRecordInfo<'/administracion/CatalogosPage', '/administracion/CatalogosPage', Record<never, never>, Record<never, never>>,
    '/administracion/ContratosReasegPage': RouteRecordInfo<'/administracion/ContratosReasegPage', '/administracion/ContratosReasegPage', Record<never, never>, Record<never, never>>,
    '/AutenticacionC': RouteRecordInfo<'/AutenticacionC', '/AutenticacionC', Record<never, never>, Record<never, never>>,
    '/catalogos/ClasificacionCoberturaPage': RouteRecordInfo<'/catalogos/ClasificacionCoberturaPage', '/catalogos/ClasificacionCoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CoberturaPage': RouteRecordInfo<'/catalogos/CoberturaPage', '/catalogos/CoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CriteriosAsignacionPage': RouteRecordInfo<'/catalogos/CriteriosAsignacionPage', '/catalogos/CriteriosAsignacionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/CriteriosCoberturaPage': RouteRecordInfo<'/catalogos/CriteriosCoberturaPage', '/catalogos/CriteriosCoberturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/DistribucionCesionPage': RouteRecordInfo<'/catalogos/DistribucionCesionPage', '/catalogos/DistribucionCesionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EntidadFederativaPage': RouteRecordInfo<'/catalogos/EntidadFederativaPage', '/catalogos/EntidadFederativaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EstatusPage': RouteRecordInfo<'/catalogos/EstatusPage', '/catalogos/EstatusPage', Record<never, never>, Record<never, never>>,
    '/catalogos/EstatusReciboPage': RouteRecordInfo<'/catalogos/EstatusReciboPage', '/catalogos/EstatusReciboPage', Record<never, never>, Record<never, never>>,
    '/catalogos/ExtensionPage': RouteRecordInfo<'/catalogos/ExtensionPage', '/catalogos/ExtensionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FormaContractualPage': RouteRecordInfo<'/catalogos/FormaContractualPage', '/catalogos/FormaContractualPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FormaPagoPage': RouteRecordInfo<'/catalogos/FormaPagoPage', '/catalogos/FormaPagoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/FumadorPage': RouteRecordInfo<'/catalogos/FumadorPage', '/catalogos/FumadorPage', Record<never, never>, Record<never, never>>,
    '/catalogos/IntermediariosPage': RouteRecordInfo<'/catalogos/IntermediariosPage', '/catalogos/IntermediariosPage', Record<never, never>, Record<never, never>>,
    '/catalogos/MonedaPage': RouteRecordInfo<'/catalogos/MonedaPage', '/catalogos/MonedaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/OperacionesRamosPage': RouteRecordInfo<'/catalogos/OperacionesRamosPage', '/catalogos/OperacionesRamosPage', Record<never, never>, Record<never, never>>,
    '/catalogos/PerfilPage': RouteRecordInfo<'/catalogos/PerfilPage', '/catalogos/PerfilPage', Record<never, never>, Record<never, never>>,
    '/catalogos/PtuPage': RouteRecordInfo<'/catalogos/PtuPage', '/catalogos/PtuPage', Record<never, never>, Record<never, never>>,
    '/catalogos/ReaseguradoresPage': RouteRecordInfo<'/catalogos/ReaseguradoresPage', '/catalogos/ReaseguradoresPage', Record<never, never>, Record<never, never>>,
    '/catalogos/SexoPage': RouteRecordInfo<'/catalogos/SexoPage', '/catalogos/SexoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoAsignacionPage': RouteRecordInfo<'/catalogos/TipoAsignacionPage', '/catalogos/TipoAsignacionPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoEndosoPage': RouteRecordInfo<'/catalogos/TipoEndosoPage', '/catalogos/TipoEndosoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoReaseguroPage': RouteRecordInfo<'/catalogos/TipoReaseguroPage', '/catalogos/TipoReaseguroPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposCambioPage': RouteRecordInfo<'/catalogos/TiposCambioPage', '/catalogos/TiposCambioPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposCapturaPage': RouteRecordInfo<'/catalogos/TiposCapturaPage', '/catalogos/TiposCapturaPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TiposContratoPage': RouteRecordInfo<'/catalogos/TiposContratoPage', '/catalogos/TiposContratoPage', Record<never, never>, Record<never, never>>,
    '/catalogos/TipoTarifaPage': RouteRecordInfo<'/catalogos/TipoTarifaPage', '/catalogos/TipoTarifaPage', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/LoginC': RouteRecordInfo<'/LoginC', '/LoginC', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/ModificarContratosPage': RouteRecordInfo<'/reaseguro/Contratos/ModificarContratosPage', '/reaseguro/Contratos/ModificarContratosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormCoberturasPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormCoberturasPage', '/reaseguro/Contratos/NuevoContrato/FormCoberturasPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormComisionesPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormComisionesPage', '/reaseguro/Contratos/NuevoContrato/FormComisionesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormConfirmacionPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormConfirmacionPage', '/reaseguro/Contratos/NuevoContrato/FormConfirmacionPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormCorretajePage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormCorretajePage', '/reaseguro/Contratos/NuevoContrato/FormCorretajePage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormDetallesPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormDetallesPage', '/reaseguro/Contratos/NuevoContrato/FormDetallesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormGeneralesPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormGeneralesPage', '/reaseguro/Contratos/NuevoContrato/FormGeneralesPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormIntermediariosPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormIntermediariosPage', '/reaseguro/Contratos/NuevoContrato/FormIntermediariosPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContrato/FormReaseguradoresPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContrato/FormReaseguradoresPage', '/reaseguro/Contratos/NuevoContrato/FormReaseguradoresPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/NuevoContratoPage': RouteRecordInfo<'/reaseguro/Contratos/NuevoContratoPage', '/reaseguro/Contratos/NuevoContratoPage', Record<never, never>, Record<never, never>>,
    '/reaseguro/Contratos/VisualizarContratosPage': RouteRecordInfo<'/reaseguro/Contratos/VisualizarContratosPage', '/reaseguro/Contratos/VisualizarContratosPage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/administracion/AdministracionPage.vue': {
      routes: '/administracion/AdministracionPage'
      views: never
    }
    'src/pages/administracion/CalculosPage.vue': {
      routes: '/administracion/CalculosPage'
      views: never
    }
    'src/pages/administracion/CatalogosPage.vue': {
      routes: '/administracion/CatalogosPage'
      views: never
    }
    'src/pages/administracion/ContratosReasegPage.vue': {
      routes: '/administracion/ContratosReasegPage'
      views: never
    }
    'src/pages/AutenticacionC.vue': {
      routes: '/AutenticacionC'
      views: never
    }
    'src/pages/catalogos/ClasificacionCoberturaPage.vue': {
      routes: '/catalogos/ClasificacionCoberturaPage'
      views: never
    }
    'src/pages/catalogos/CoberturaPage.vue': {
      routes: '/catalogos/CoberturaPage'
      views: never
    }
    'src/pages/catalogos/CriteriosAsignacionPage.vue': {
      routes: '/catalogos/CriteriosAsignacionPage'
      views: never
    }
    'src/pages/catalogos/CriteriosCoberturaPage.vue': {
      routes: '/catalogos/CriteriosCoberturaPage'
      views: never
    }
    'src/pages/catalogos/DistribucionCesionPage.vue': {
      routes: '/catalogos/DistribucionCesionPage'
      views: never
    }
    'src/pages/catalogos/EntidadFederativaPage.vue': {
      routes: '/catalogos/EntidadFederativaPage'
      views: never
    }
    'src/pages/catalogos/EstatusPage.vue': {
      routes: '/catalogos/EstatusPage'
      views: never
    }
    'src/pages/catalogos/EstatusReciboPage.vue': {
      routes: '/catalogos/EstatusReciboPage'
      views: never
    }
    'src/pages/catalogos/ExtensionPage.vue': {
      routes: '/catalogos/ExtensionPage'
      views: never
    }
    'src/pages/catalogos/FormaContractualPage.vue': {
      routes: '/catalogos/FormaContractualPage'
      views: never
    }
    'src/pages/catalogos/FormaPagoPage.vue': {
      routes: '/catalogos/FormaPagoPage'
      views: never
    }
    'src/pages/catalogos/FumadorPage.vue': {
      routes: '/catalogos/FumadorPage'
      views: never
    }
    'src/pages/catalogos/IntermediariosPage.vue': {
      routes: '/catalogos/IntermediariosPage'
      views: never
    }
    'src/pages/catalogos/MonedaPage.vue': {
      routes: '/catalogos/MonedaPage'
      views: never
    }
    'src/pages/catalogos/OperacionesRamosPage.vue': {
      routes: '/catalogos/OperacionesRamosPage'
      views: never
    }
    'src/pages/catalogos/PerfilPage.vue': {
      routes: '/catalogos/PerfilPage'
      views: never
    }
    'src/pages/catalogos/PtuPage.vue': {
      routes: '/catalogos/PtuPage'
      views: never
    }
    'src/pages/catalogos/ReaseguradoresPage.vue': {
      routes: '/catalogos/ReaseguradoresPage'
      views: never
    }
    'src/pages/catalogos/SexoPage.vue': {
      routes: '/catalogos/SexoPage'
      views: never
    }
    'src/pages/catalogos/TipoAsignacionPage.vue': {
      routes: '/catalogos/TipoAsignacionPage'
      views: never
    }
    'src/pages/catalogos/TipoEndosoPage.vue': {
      routes: '/catalogos/TipoEndosoPage'
      views: never
    }
    'src/pages/catalogos/TipoReaseguroPage.vue': {
      routes: '/catalogos/TipoReaseguroPage'
      views: never
    }
    'src/pages/catalogos/TiposCambioPage.vue': {
      routes: '/catalogos/TiposCambioPage'
      views: never
    }
    'src/pages/catalogos/TiposCapturaPage.vue': {
      routes: '/catalogos/TiposCapturaPage'
      views: never
    }
    'src/pages/catalogos/TiposContratoPage.vue': {
      routes: '/catalogos/TiposContratoPage'
      views: never
    }
    'src/pages/catalogos/TipoTarifaPage.vue': {
      routes: '/catalogos/TipoTarifaPage'
      views: never
    }
    'src/pages/Home.vue': {
      routes: '/Home'
      views: never
    }
    'src/pages/LoginC.vue': {
      routes: '/LoginC'
      views: never
    }
    'src/pages/reaseguro/Contratos/ModificarContratosPage.vue': {
      routes: '/reaseguro/Contratos/ModificarContratosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormCoberturasPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormCoberturasPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormComisionesPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormComisionesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormConfirmacionPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormConfirmacionPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormCorretajePage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormCorretajePage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormDetallesPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormDetallesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormGeneralesPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormGeneralesPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormIntermediariosPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormIntermediariosPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContrato/FormReaseguradoresPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContrato/FormReaseguradoresPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/NuevoContratoPage.vue': {
      routes: '/reaseguro/Contratos/NuevoContratoPage'
      views: never
    }
    'src/pages/reaseguro/Contratos/VisualizarContratosPage.vue': {
      routes: '/reaseguro/Contratos/VisualizarContratosPage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
